inseq-team/inseq

docs/source/_static/inseq.js, inseq/models/huggingface_model.py
As highlighted in huggingface/transformers#20825 the default setting for `max_new_tokens` in the `HuggingfaceModel` class was causing some problems with generation due to conflicts between `max_new_tokens` and `max_length` in :hugs: transformers. For example:
```python
import inseq
model = inseq.load_model("facebook/wmt19-en-de", "integrated_gradients")
out = model.attribute("The developer argued with the designer because her idea cannot be implemented.")
```
would produce the error
```shell
ValueError: Both `max_new_tokens` and `max_length` have been set but they serve the same purpose -- setting a limit to the generated output length. Remove one of those arguments. Please refer to the documentation for more information. 
(https://huggingface.co/docs/transformers/main/en/main_classes/text …
```
=> Fix conflicting generation args

inseq/models/huggingface_model.py
Currently, when using attribution methods requiring baselines (e.g. `integrated_gradients`) the default behavior is to exclude the source end-of-string token from the attribution by setting it to the same index in the baseline. This setting was however assuming that the EOS token id was always 0, which is not the case for most models, producing unwanted attributions on the EOS token. This PR fixes this behavior by ensuring that the correct token id is set in the baseline for the EOS.
=> Fix EOS baseline for models with `pad_token_id` != 0

inseq/attr/feat/feature_attribution.py, inseq/commands/attribute.py, inseq/models/attribution_model.py
This PR introduces a `generate_from_target_prefix` argument in the `model.attribute` method and the `inseq attribute` CLI, allowing the usage of pre-specified `generated_text` as a prefix for the model to complete, rather than a finished generation.
This functionality exploits the capabilities of the `generate` function in :hugs: transformers, and is restricted to encoder-decoder models only, since controlling the prefix is handled through the `input_text` parameter for decoder-only models. The same behavior could already be achieved in inseq v0.4 by providing explicit `decoder_input_ids`  as `generation_args`.
**Current behavior:**
```python
>>> import inseq
>>> m = inseq.load_model("Helsinki-NLP/opus-mt-en-it", "saliency")
>>> prefix_ids = m.encode("Hey mondo!", as_targets=True)
>>> out …
```
=> Target prefix-constrained generation

docs/source/examples/locate_gpt2_knowledge.rst
Fixes minor syntax and naming errors in the `locate_gpt2_knowledge` example tutorial in the documentation
=> Fix Locate GPT-2 Knowledge tutorial in docs

inseq/models/huggingface_model.py
This PR extends the logic that prevents calling `.to` on 8bit quantized HF models to models loaded with 4bit quantization.
- 🥂 Improvement (non-breaking change which improves an existing feature)
=> Handle .to for 4bit quantized models

inseq/data/attribution.py, tests/data/test_attribution.py
Fixes exporting `get_scores_dicts` for generations starting at non-initial positions (i.e. when `attr_pos_start != 0`, like for decoder-only models), reported broken by #185 
=> Fix `get_scores_dicts` for non-initial `attr_pos_start`

inseq/data/attribution.py
At the moment the presence of duplicate tokens in either the source or the target sentence produces a malformed dictionary when `out.get_scores_dict` is called due to the unicity requirement of dict keys. This PR fixes the issue by using tuples of `token_idx, token` as keys for the different dictionary field.
- 💥 Breaking change (fix or feature that would cause existing functionality to change)
=> Fix `get_scores_dict` for duplicate tokens

inseq/attr/feat/feature_attribution.py
This PR removes the forced seed in the `filtered_attribution_step`, as it is not currently used.
=> Remove forced seed in attribution

inseq/data/attribution.py, tests/fixtures/huggingface_model.json, tests/models/test_huggingface_model.py
Fixes an incompatibility for decoder-only models in the `remap_from_filtered` method that was producing an error when used with batch_size > 1.
=> Fix attribution remapping for decoder-only models

docs/source/examples/custom_attribute_target.rst, docs/source/examples/tuned_lens.rst, docs/source/main_classes/step_functions.rst, inseq/attr/__init__.py, inseq/attr/feat/feature_attribution.py, inseq/attr/step_functions.py, inseq/data/viz.py, inseq/models/attribution_model.py, inseq/models/decoder_only.py, inseq/models/encoder_decoder.py, inseq/utils/__init__.py, inseq/utils/torch_utils.py, tests/attr/feat/test_attribution_utils.py, tests/attr/feat/test_feature_attribution.py
This PR adds the following capabilities to the Inseq library:
- A new `top_p_size_fn` (identifier: `"top_p_size"`) step function returning the number of tokens needed to reach probability `p` for a specific generation step (e.g. 5 with `p=0.95` means that the top 5 tokens in the probability distribution over the vocabulary are needed to reach a [CDF](https://en.wikipedia.org/wiki/Cumulative_distribution_function) of 95%)
- The `kl_divergence` step function now supports a new parameter `top_p: float` defined in [0,1] (default 1, full distribution) to preserve only tokens in the top p of either the original or the contrastive output distributions before computing the KL divergence between the two.
:fire:  **Breaking change**: This PR introduces a new `StepFunctionArgs` to better structure …
=> Add `top_p_size` step fn, `StepFunctionArgs` class

README.md, inseq/attr/feat/attribution_utils.py, inseq/attr/feat/feature_attribution.py, inseq/models/attribution_model.py, inseq/utils/alignment_utils.py
At the moment, contrastive attribution cannot be performed using a substring of the original inputs as `contrast_targets`. This is an important limitation since one might want to attribute which parts of the original additional contest is influencing the predictions compared to a contrastive alternative lacking context. To illustrate this issue, in the following example we can see that the token "Jungle" is 41% less likely without the prefix mentioning Guns N' Roses, but we cannot attribute this difference to the prefix since it is not part of the original input:
```python
import inseq
model = inseq.load_model("gpt2", "saliency")
out = model.attribute(
"Welcome to",
"Welcome to the Jungle",
"contrast_prob_diff",
contrast_target_prefixes="The recent song by Guns N' Roses,", …
```
=> Allow contrastive attribution with shorter contrastive targets

docs/source/main_classes/main_functions.rst, inseq/__init__.py, inseq/data/__init__.py, inseq/data/attribution.py, inseq/models/attribution_model.py
The merge_attributions method is moved out of the FeatureAttributionOutput class as described in #209.
Fix #209 
- 💥 Breaking change (fix or feature that would cause existing functionality to change)
=> fix `merge_attributions`

inseq/data/aggregation_functions.py, inseq/data/aggregator.py, inseq/data/viz.py, tests/data/test_aggregator.py
This PR solves issues in the handling of `attr_pos_start` and `attr_pos_end` when using `ContiguousSpanAggregator`. In particular, it enables using the aggregator when `attr_pos_start != 0` to obtain the correct results.
=> Support `ContiguousSpanAggregation` when `attr_pos_start != 0`

inseq/models/huggingface_model.py
Fixes #198 by forcing `clean_up_tokenization_spaces=False` at in `HuggingfaceModel.decode`, ensuring consistency between `input_texts` and `generated_texts` for decoder-only models.
=> Fix tokenization space cleanup

README.md, docs/source/main_classes/feature_attribution.rst, inseq/attr/feat/__init__.py, inseq/attr/feat/gradient_attribution.py, inseq/attr/feat/internals_attribution.py, inseq/attr/feat/ops/__init__.py, inseq/attr/feat/ops/discretized_integrated_gradients.py, inseq/attr/feat/ops/lime.py, inseq/attr/feat/ops/sequential_integrated_gradients.py, inseq/models/model_config.py
This PR adds the Sequential Integrated Gradient attribution method by [Enguehard (2023)](https://aclanthology.org/2023.findings-acl.477/) (@josephenguehard). Provided a Captum-compatible implementation was already available in the original [time_interpret](https://github.com/josephenguehard/time_interpret/tree/main) library, I simply copied the class under the `attr/ops` folder, and added the required wrapper to enable sequential usage.
Example usage:
```python
import inseq
m = inseq.load_model("gpt2", "sequential_integrated_gradients") 
out = m.attribute("What is the capital of Cambodia?")
out.show()
```
=> Add Sequential IG method

README.md, docs/source/main_classes/step_functions.rst, inseq/attr/step_functions.py, inseq/utils/__init__.py, inseq/utils/torch_utils.py, tests/utils/test_torch_utils.py
This PR:
- Fixes the top-k and top-p filtering for the `kl_divergence` step function with a more general utility function
- Adds pre-registered `contrast_logit_fn` and `contrast_logit_diff_fn`, equivalent to `contrast_prob_fn` and `contrast_prob_diff_fn` but using pre-softmax logits instead of probabilities.
- Add the `logprobs` boolean parameter to `probability_fn`, `contrast_prob_fn`, `contrast_prob_diff_fn` and `mc_dropout_prob_avg_fn` to allow for using `F.log_softmax` log-probabilities instead of `F.softmax` probabilities (default behavior)
- Add the `in_context_pvi` step function for calculating in-context pointwise V-usable information [(Lu et al. 2023)](https://arxiv.org/abs/2310.12300), using @boblus implementation from [boblus/in-context-pvi](https://github.com/boblus/in-context- …
=> Step functions fixes, add `in_context_pvi`

inseq/models/huggingface_model.py
Removing the logic to impose a `max_length` in absence of pre-specified max input size in model configuration. Closes #221.
=> Remove `max_input_length` from `model.encode`

CONTRIBUTING.md
`make pre-commit-install` does not exist any longer, `make install-dev` seems to be the right choice now.
- 📚 Examples / docs / tutorials / dependencies update
=> Fix command for installing pre-commit hooks.

inseq/attr/feat/feature_attribution.py, inseq/attr/step_functions.py, inseq/data/batch.py, inseq/models/attribution_model.py, inseq/models/decoder_only.py, inseq/models/encoder_decoder.py, inseq/utils/alignment_utils.py, inseq/utils/contrast_utils.py, tests/attr/feat/test_step_functions.py
This PR:
- Reorganizes logics related to contrastive step functions in the `contrast_utils` module.
- Add the `is_attributed_fn` bool flag (default: `False`) to the `StepFunctionBaseArgs` class. This flag enables custom behavior during step function execution by checking whether the function is being called as a step function or as an attribution target.
- Fix the problematic behavior of `contrast_prob_diff` as an attributed function (#188) by forcing original inputs at every step when
performing contrastive feature attribution (matching [Yin and Neubig (2022)](https://aclanthology.org/2022.emnlp-main.14/) implementation). The previous behavior allowing for measuring contrastive probability difference in presence of different input sources is preserved when the function is used as step …
=> Attributed behavior for contrastive step functions

README.md, inseq/attr/feat/internals_attribution.py, inseq/attr/step_functions.py, inseq/data/attribution.py, pyproject.toml
Minor bugfixes for contrastive attribution and encoder sequence scores conversion
=> Minor fixes

README.md, poetry.lock, pyproject.toml
Inseq does not work with older `jaxlib` versions.
This adds an optional `jax` group that specified the `jax` and `jaxlib` dependencies.
Closes #234 
- 🥂 Improvement (non-breaking change which improves an existing feature)
- ~~[ ] I've written tests for all new methods and classes that I created and successfully ran `make test`.~~
- ~~[ ] I've written the docstring in Google format for all the methods and classes that I used.~~
=> Add optional jax group to enforce compatible jaxlib version.

inseq/data/aggregator.py, inseq/utils/torch_utils.py, tests/data/test_aggregator.py
Fixes the `aggregate_contiguous` function used by `ContiguousSpanAggregator` and `SubwordAggregator` classes in the edge case of single-step generation described by #246. Also adjusts the function behavior to avoid unnecessary transpositions and squeeze/unsqueeze operations whenever possible.
=> Fix `aggregate_contiguous`

inseq/attr/feat/feature_attribution.py, inseq/attr/feat/gradient_attribution.py, inseq/data/aggregator.py, inseq/data/attribution.py
Potential fix for failed `test_attribute_slice_seq2seq` on CUDA-enabled platforms
Issue https://github.com/inseq-team/inseq/issues/251
=> Potential fix for failed `test_attribute_slice_seq2seq` on CUDA-enabled platforms

inseq/attr/feat/feature_attribution.py
Ensures the outcome of the `attribute_step` method is always on `cpu` to minimize GPU memory allocation, while also preventing device issues raised in #251
=> Fix casting step outputs to device

docs/source/main_classes/cli.rst
The URL was missing a digit, resulting in a link to an unrelated paper.
- 📚 Examples / docs / tutorials / dependencies update
=> Fix URL to arXiv

docs/source/conf.py, inseq/models/attribution_model.py, inseq/models/huggingface_model.py, inseq/utils/__init__.py, inseq/utils/import_utils.py, pyproject.toml
This PR adds support for using a custom `device_map` in the loaded HF model, avoiding to cast it to a device in `AttributionModel.setup()` if the device map is specified, and dispatching it using the `accelerate.dispatch_model` method instead.
=> Add support for `device_map` use

inseq/attr/feat/ops/value_zeroing.py, inseq/models/huggingface_model.py, inseq/utils/__init__.py, inseq/utils/hooks.py
This PR addresses the bug with SDPA attention described in #266, and enables the usage of VZ out of the box for all attention implementations
=> Support Value Zeroing for non-eager attention types

inseq/attr/feat/internals_attribution.py, inseq/models/huggingface_model.py
- Fix the issue in the attention implementation from #268 where non-terminal position in the tensor were set to nan if they were 0s
- Fix the pad token in cases where it is not specified by default in the loaded model
=> Fix nans in attention, add pad in tokenizer if missing

inseq/attr/feat/feature_attribution.py, inseq/attr/step_functions.py, inseq/data/attribution.py, inseq/models/attribution_model.py, inseq/models/decoder_only.py, inseq/models/encoder_decoder.py, inseq/models/huggingface_model.py, inseq/utils/contrast_utils.py, requirements-dev.txt, requirements.txt
This PR addresses the possibility of skipping special tokens during attribution using the `skip_special_tokens=True` argument.
Example usage (regular attribution):
```python
import inseq
model = inseq.load_model("mymusise/CPM-Generate-distill", "integrated_gradients")
out = model.attribute(
input_texts=["她们是飞行员还是制片人", "她们是飞行员还是制片人"],
generated_texts=["她们是飞行员还是制片人？", "她们是飞行员还是制片人吗？"],
step_scores=["probability"],
skip_special_tokens=True,
)
out.show()
```
Example usage (contrastive attribution):
```python
import inseq
model = inseq.load_model("mymusise/CPM-Generate-distill", "saliency")
out = model.attribute(
input_texts="她们是飞行员还是制片人",
generated_texts="她们是飞行员还是制片人？",
skip_special_tokens=True, # New argument to skip special tokens
contrast_targets="她们是飞行员还是制片人吗", …
```
=> Add possibility to skip special tokens during attribution

inseq/data/aggregator.py, pyproject.toml, requirements-dev.txt
This PR introduces `StringSplitAggregator` (nickname for `aggregate` usage: `"split"`), supporting aggregating on token groups after splitting on arbitrary substrings.
Example usage:
```python
out.aggregate("split", split_pattern="\n").aggregate("sum").show(do_aggregation=False)
out.aggregate("split", split_pattern=r"\s(\w{5})(?=\s)", split_mode="end")
```
Example multi-example prompt with newline splitting:
`split_mode = "single"`
`split_mode= = "start"` (sequences begin with \n)
`split_mode= = "end"` (sequences end with \n)
=> Add `StringSplitAggregator`

CHANGELOG.md, inseq/data/aggregator.py, inseq/data/attribution.py
This PR fixes the issue highlighted in #291 in which the information contained in configuration attributes (preceded by `_`) in `FeatureAttributionSequenceOutput` classes was not copied over after calling `out.aggregate`. This was causing methods like `value_zeroing` to break, since the default `MultiDimensionalFeatureAttributionSequenceOutput` output was assumed to be 4-dimensional from the `attention` method.
In the updated version, a new property `config` was added to `FeatureAttributionSequenceOutput` to easily access all configuration attributes, and the resulting properties are now updated correctly.
=> Fix `MultiDimensional` attribution aggregation
